config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  post 'users/confirmation', to: 'users#confirm_email'

  concern :votable do
    member do
      post :like
      post :dislike
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: %i[create]
  end

  resources :questions, shallow: true, concerns: %i[votable commentable] do
    resources :answers, shallow: true, except: :index, concerns: %i[votable commentable] do
      member do
        patch :best
      end
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachments, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :awards, only: %i[index]

  get :search, to: 'search#index'

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show update create destroy]
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord

  include Votable
  include Commentable

  belongs_to :user

  has_many :answers, -> { order(best: :desc) }, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  has_one :award, dependent: :destroy
  has_many_attached :files

  accepts_nested_attributes_for :links, :award, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true

  after_create :calculate_reputation
  after_create :subscription_author

  def user_subscription?(user)
    subscriptions.find_by(user: user)
  end

  private

  def subscription_author
    subscriptions.create(user: user)
  end

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  def index
    questions = Question.all
    render json: questions
  end

  def show
    render json: question, serializer: Api::V1::QuestionSerializer
  end

  def create
    question = current_resource_owner.questions.new(question_params)

    if question.save
      render json: question, status: :created
    else
      render json: { errors:question.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize question

    if question.update(question_params)
      render json: question, status: :created
    else
      render json: { errors:question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize question

    if question.destroy
      render json: question, status: :ok
    else
      render json: { errors: 'Question delete.' }, status: :unprocessable_entity
    end
  end

  private

  def question
    @question ||= Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(
      :title,
      :body,
      :user_id,
      links_attributes: [:name, :url, :_destroy]
    )
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show update destroy]

  def index
    @questions = Question.all
  end

  def show
    gon.question_id = @question.id
    gon.user_id = current_user&.id
    @subscription = @question.subscriptions.find_by(user: current_user)
    @answer = Answer.new
    @answers = @question.answers
    @answer.links.new
  end

  def new
    @question = Question.new
    @question.links.new
    @award = Award.new(question: @question)
  end

  def create
    @question = Question.new(question_params)

    @question.user = current_user

    if @question.save
      ActionCable.server.broadcast 'questions_channel', @question
      redirect_to @question, notice: 'Your question successfully created.'
    end
  end

  def update
    authorize @question
    @question.update(question_params)
    @subscription = @question.subscriptions.find_by(user: current_user)
  end

  def destroy
    authorize @question
    @question.destroy

    redirect_to root_path, notice: 'Question successfully deleted!'
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [],
                                      links_attributes: [:name, :url, :_destroy],
                                      award_attributes: [:title, :image])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
- if current_user.present?
  .question-errors
    = render 'shared/errors', resource: @question
  .question_block
    = form_with model: @question, local: false do |f|
      p= f.label :title
      p= f.text_field :title
      p= f.label :body
      p= f.text_area :body
      p= f.label :files
      p= f.file_field :files, multiple: true

      p Links:
      #question_links
        = f.fields_for :links do |l|
        .links
        p= link_to_add_association 'Add link', f, :links,
          partial: 'links/link'

      .award
        b Award setup:
        = f.fields_for :award do |a|
          p= a.label :title, 'Award title'
          p= a.text_field :title
          p= a.label :image, 'Select image'
          p= a.file_field :image, direct_upload: true

      p= f.submit 'Ask'

app/views/questions/_question.html.slim
.questions_main class=["question-id-#{@question.id}"] id="question-#{@question.id}" data-question-id="#{@question.id}"
  .question-error
    = render 'shared/errors', resource: @question
  .question_title
    = @question.title
  .question-body
    = @question.body
  .subscription
    - if current_user
      = render 'subscribe'

  p

  = render partial: 'votes/vote', locals: { votable: @question }

  - if @question.files.attached?
    - @question.files.each do |file|
      p.attachment id="attachment-#{file.id}"
        = link_to file.filename.to_s, url_for(file)
        - if policy(@question).destroy?
          = " | "
          = link_to 'Delete attachment', attachment_path(file), method: :delete, remote: true

  p

  - @question.links.each do |link|
    div id="link-delete-#{link.id}"
      .link-name
        = link_to link.name, link.url
        - if policy(@question).destroy?
          = " | "
          = link_to 'Delete link', link_path(link), method: :delete, remote: true

  p

  - if @question.award.present?
    b Award:
    = image_tag url_for(@question.award.image)

  p

  .question-controls
    - if policy(@question).destroy?
      = link_to 'Delete question', question_path(@question), class: 'btn btn-danger', method: :delete
    - if policy(@question).update?
      = " | "
      = link_to 'Edit', '#', class: 'btn btn-info edit-question-link', data: { question_id: @question.id }

      = form_with model: @question, local: false, class: 'hidden', html: { id: "edit-question-#{@question.id}" } do |f|
        p= f.label :title, 'Title'
        p= f.text_field :title
        p= f.label :body, 'Body'
        p= f.text_area :body
        p= f.label :files
        p= f.file_field :files, multiple: true

        p= f.fields_for :links do |l|
        .links
          p= link_to_add_association 'Add link', f, :links,
              partial: 'links/link'
        p= f.submit 'Save', class: 'btn btn-success'

  p= "Comments:"

  div class="comment_question_#{question.id}"
    .comments
      = render @question.comments
    - if current_user
      .comment-form
        = render 'comments/form', commentable: @question

app/views/questions/_subscribe.html.slim
.subscription
  - if @question.user_subscription?(current_user)
    = link_to 'Delete subscribe', subscription_path(@subscription), method: :delete, remote: true
  - else
    = link_to 'Subscribe', question_subscriptions_path(@question), method: :post, remote: true

app/views/questions/create.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');
var event = new Event('gist:updated');
document.dispatchEvent(event);

app/views/questions/index.html.slim
.question_block
  = link_to 'Ask question', new_question_path

- cache collection_cache_key_for :question do
  .question_block_main
    - @questions.each do |question|
      p= link_to question.title, question

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
- cache @question do
  .question-container
    = render @question

  .answers
    = render @question.answers
  = render 'answers/form'

app/views/questions/update.js.erb
$('.question-error').html('<%= render 'shared/errors', resource: @question %>')

<% if !@question.errors.present? %>
  $('.question-container .questions_main').remove()
  $('.question-container').append('<%= j render @question %>')
  var event = new Event('gist:updated')
  document.dispatchEvent(event)
<% end %>