config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  root to: 'questions#index'

  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  post 'users/confirmation', to: 'users#confirm_email'

  concern :votable do
    member do
      post :like
      post :dislike
    end
  end

  concern :commentable do
    resources :comments, shallow: true, only: %i[create]
  end

  resources :questions, shallow: true, concerns: %i[votable commentable] do
    resources :answers, shallow: true, except: :index, concerns: %i[votable commentable] do
      member do
        patch :best
      end
    end
    resources :subscriptions, shallow: true, only: %i[create destroy]
  end

  resources :attachments, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :awards, only: %i[index]

  get :search, to: 'search#index'

  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[index show update create destroy]
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord

  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user

  has_many_attached :files
  has_many :links, dependent: :destroy, as: :linkable
  has_one :award, dependent: :destroy

  validates :body, presence: true

  accepts_nested_attributes_for :links, :award, reject_if: :all_blank, allow_destroy: true

  after_create :notify_question_subscribers

  def set_best
    Answer.transaction do
      Answer.where(question_id: question_id, best: true).update_all(best: false)
      update!(best: true)
      if question.award
        update!(award: question.award)
      end
    end
  end

  private

  def notify_question_subscribers
    QuestionNotificationsJob.perform_later(question)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  include Voted

  before_action :authenticate_user!, only: %i[create update destroy best]
  before_action :find_question, only: %i[create]
  before_action :load_answer, only: %i[update destroy best]

  def edit; end

  def create
    authorize Answer
    @answer = @question.answers.create(answer_params)
    @answer.user = current_user
    publish_answer if @answer.save
    @answer_comment = @answer.comments.new
  end

  def update
    authorize @answer
    @question = @answer.question
    @answer.update(answer_params)
  end

  def destroy
    authorize @answer
    @answer.destroy
  end

  def best
    authorize @answer
    @question = @answer.question

    return unless current_user.author?(@question)

    @answer.set_best
  end

  private

  def publish_answer
    html = ApplicationController.render(
      partial: 'answers/answer_block',
      locals: { answer: @answer }
    )

    ActionCable.server.broadcast("question_answers_channel_#{@question.id}",
                                 { html: html, author_id: @answer.user.id })
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [],
                                    links_attributes: [:name, :url, :_destroy],
                                    award_attributes: [:title, :image])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  def index
    @answers = question.answers
    render json: @answers
  end

  def show
    render json: answer, serializer: Api::V1::AnswerSerializer
  end

  def create
    answer = question.answers.build(answer_params.merge(user: current_resource_owner))

    if answer.save
      render json: answer, status: :created
    else
      render json: { errors: answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize answer

    if answer.update(answer_params)
      render json: answer, status: :created
    else
      render json: { errors: answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize answer
    
    if answer.destroy
      render json: answer, status: :ok
    else
      render json: { errors: 'Answer not delete.' }, status: :unprocessable_entity
    end
  end

  private

  def question
    @question ||= Question.find(params[:question_id])
  end
  
  def answer
    @answer ||= question.answers.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
.answer id="answer-#{answer.id}" class=["answer-id-#{answer.id}" " #{answer.best? ? 'best-answer' : ''}"]
  p
    .answer_block
      = answer.body

      = render partial: 'votes/vote', locals: { votable: answer }

      p
        - if answer.files.attached?
          - answer.files.each do |file|
            .attachment id="attachment-#{file.id}"
              = link_to file.filename.to_s, url_for(file)
              - if policy(answer).destroy?
                = " | "
                = link_to 'Delete attachment', attachment_path(file), method: :delete, remote: true, class: 'attachmentss'

      p
        - answer.links.each do |link|
          div id="link-delete-#{link.id}"
            .link-name
              = link_to link.name, link.url
              - if policy(answer).destroy?
                = " | "
                = link_to 'Delete link', link_path(link), method: :delete, remote: true

      p
        - if policy(answer).destroy?
          = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true, class: 'btn btn-danger delete-answer-link', data: { answer_id: answer.id }
        - if policy(answer).update?
          = " | "
          = link_to 'Edit', '#', class: 'btn btn-info edit-answer-link', data: { answer_id: answer.id }

        - if policy(answer.question).update? && !answer.best?
          p= link_to 'Best answer', best_answer_path(answer),
            remote: true, method: :patch, class: 'btn btn-info best-answer-link', data: { answer_id: answer.id }

        div class=["answer-error-#{answer.id}"]

        = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
          = f.label :body, 'Your answer'
          p= f.text_area :body
          p= f.label :files, 'Files:'
          p= f.file_field :files, multiple: true
          p Links:
          p= f.fields_for :links do |l|
          .links
            p= link_to_add_association 'Add link', f, :links, partial: 'links/link'
          p= f.submit 'Save', class: 'btn btn-success'

        p
        p= "Comments:"

        div class="comment_answer_#{answer.id}"
          .comments
            = render answer.comments
          - if current_user
            .comment-form
              = render 'comments/form', commentable: answer
  

app/views/answers/_answer_block.html.slim
.answer_block
  = answer.body

  .votes
    .wrapper
      .rating
        = answer.rating
      .like
        i.fa.fa-thumbs-o-up class="fa-lg"
      .dislike
        i.fa.fa-thumbs-o-down class="fa-lg"

  p
    - if answer.files.attached?
      - answer.files.each do |file|
        .attachment id="attachment-#{file.id}"
          = link_to file.filename.to_s, url_for(file)

  p
    - answer.links.each do |link|
      div id="link-delete-#{link.id}"
        .link-name
          = link_to link.name, link.url

  p
  div class="comment_answer_#{answer.id}"
    .comments
      = render answer.comments

app/views/answers/_form.html.slim
.answer-errors
  = render 'shared/errors', resource: @answer

.answer_block_create
  - if current_user.present?
    = form_with model: [@question, @answer], local: false, class: 'new-answer', data: { type: :json } do |f|
      p= f.label :body, 'Your answer'
      p= f.text_area :body
      p Links:
      #answer_links
        = f.fields_for :links do |l|
        .links
          p= link_to_add_association 'Add link', f, :links,
            partial: 'links/link'
      p= f.label :files, 'Files:'
      p= f.file_field :files, multiple: true
      = f.submit 'Create Answer'

app/views/answers/best.js.erb
<% if @answer.persisted? %>
  $('.answers').html('<%= j render @question.answers %>');
<% end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
  var event = new Event('gist:updated');
  document.dispatchEvent(event);
<% end %>

app/views/answers/destroy.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.destroyed? %>
  $('.answers .answer-id-<%= @answer.id %>').remove();
<% end %>

app/views/answers/update.js.erb
$('.answers .answer-error-<%= @answer.id %>').html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present? %>
  $('.answers .answer-id-<%= @answer.id %>').remove();
  $('.answers').html('<%= j render @question.answers %>');
  var event = new Event('gist:updated');
  document.dispatchEvent(event);
<% end %>